// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "ship":return img`
.......fff.......
......fbbbf......
......fdddf......
.....fbcccbf.....
.....fbc1fbf.....
.....fbfffbf.....
....fdbfffbdf....
....fdbfffbdf....
....fdcfffcdf....
....fdcdddcdf....
ff..fdcdddcdf..ff
fbf.fdcdddcdf.fbf
fbf.fdcdddcdf.fbf
fbf.fccdddccf.fbf
fcfffcfcdcfcfffcf
fccffffcccfffffcf
fccfffffffffffccf
fccffbfdddfbffccf
fcf.fffbbbfff.fcf
fff..fffffff..fff
fbf.fffbbbfff.fbf
fcf.fffffffff.fcf
fcf.f5fbbbf5f.fcf
fff.fffffffff.fff
`;
            case "image2":
            case "enemy ship 2":return img`
. . . . . . . f f . . . . . . . 
. f f . . . . f f . . . . f f . 
f f f f . . f f f f . . f f f f 
f 7 7 f . f f f f f f . f 7 7 f 
f 7 7 f f f 7 f f 7 f f f 7 7 f 
f f f f 5 f 7 f f 7 f 5 f f f f 
f 7 7 f 5 f 7 f f 7 f 5 f 7 7 f 
f 7 7 f f f 7 f f 7 f f f 7 7 f 
f f f f . f f 7 7 f f . f f f f 
f 7 7 f . . f f f f . . f 7 7 f 
f f 7 f . . f 7 7 f . . f 7 f f 
. f f f . . f 8 8 f . . f f f . 
. . f f . . f 8 8 f . . f f . . 
. . . . . . f 8 8 f . . . . . . 
. . . . . . f 7 7 f . . . . . . 
. . . . . . . f f . . . . . . . 
`;
            case "image3":
            case "enemy ship 1":return img`
. . . . . . . f f . . . . . . . 
. . . f f . f f f f . f f . . . 
. . . f f f f 2 2 f f f f . . . 
. . f f f f f f f f f f f f . . 
. f f 2 2 f 5 2 2 5 f 2 2 f f . 
f 2 2 2 2 f 2 2 2 2 f 2 2 2 2 f 
f f f f f f 2 6 6 2 f f f f f f 
f 5 5 f 2 f 2 9 9 2 f 2 f 5 5 f 
f f f f f f 2 9 9 2 f f f f f f 
f 5 5 f . f 2 2 2 2 f . f 5 5 f 
f f f f . f 2 2 2 2 f . f f f f 
f 2 2 f . f 2 2 2 2 f . f 2 2 f 
f 2 2 f . . f 2 2 f . . f 2 2 f 
f 2 2 f . . . f f . . . f 2 2 f 
f 2 2 f . . . . . . . . f 2 2 f 
. f f f . . . . . . . . f f f . 
`;
            case "image4":
            case "player projectile":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . 2 2 . . . . . . . 
. . . . . . 2 1 1 2 . . . . . . 
. . . . . . 2 1 1 2 . . . . . . 
. . . . . . . 2 2 . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image5":
            case "enemy projectile":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . 7 7 . . . . . . . 
. . . . . . 7 1 1 7 . . . . . . 
. . . . . . 7 1 1 7 . . . . . . 
. . . . . . . 7 7 . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image6":
            case "boss":return img`
........................................................................
........................................................................
........................................................................
........................................................................
................................ffffff..................................
................................fccccf..................................
...............................fbbbbbbf.................................
..............................fbbbbbbbbf................................
.............................fbbbbbbbbbbf...............................
............................ffbbbbbbbbbbff..............................
............................fbbbcbbbbcbbbf..............................
............................fbbbccccccbbbf..............................
....................ff...ffffbbbcffffcbbbffff...ff......................
...................fbbfffbbbfbbbcbbbbcbbbfbbbfffbbf.....................
..................fbbbbbbbbbfbbbffffffbbbfbbbbbbbbbf....................
..................fbbbbbbbbbfbbbfcbbcfbbbfbbbbbbbbbf....................
..................fbbfbbbbbbfbbbcbbbbcbbbfbbbbbbfbbf....................
..................fbbfbbbbbbfbbbffffffbbbfbbbbbbfbbf....................
..................fbbffffffffbbbfbbbbfbbbffffffffbbf....................
..................fffffccccffbbbfbbbbfbbbffccccfffff....................
...................fffcccccffbbbffffffbbbffcccccfff.....................
...................ffffffffffbbbbbbbbbbbbffffffffff.....................
.....................ffffffffbbbbbbbbbbbbffffffff.......................
..........fff...........ffccfbbbbbbbbbbbbfccff...........fff............
.........ffbbf..........fcccfbbbbbbbbbbbbfcccf..........fbbff...........
.........fbbbf..........fcccfbbbbbbbbbbbbfcccf..........fbbbf...........
........fbbbbf.........ffccfbbbbbbbbbbbbbbfccff.........fbbbbf..........
........fbbbbf.........fffbbbbbbbbbbbbbbbbbbfff.........fbbbbf..........
.......fbbbbbf......fffccfbbbbbbbbbbbbbbbbbbfccfff......fbbbbbf.........
.......fbbbbff....fffffccfbbbbbcffffffcbbbbbfccfffff....ffbbbbf.........
.......fbbffbbffffbbbbfccfbbbbbccccccccbbbbbfccfbbbbffffbbffbbf.........
.......fbbfbbfcccfbbbbfccfbbbbbbbbbbbbbbbbbbfccfbbbbfcccfbbfbbf.........
.......fbbfbbfcccfbbbbfccfbbbbbbbbbbbbbbbbbbfccfbbbbfcccfbbfbbf.........
.......fbbfbbfcccfbbbbfccfbbbbbbbbbbbbbbbbbbfccfbbbbfcccfbbfbbf.........
.......fbbfbbfcccfbbbbfccfbbbbbbbbbbbbbbbbbbfccfbbbbfcccfbbfbbf.........
.......fbbfbbfcccfbbbbfccfbbbbbbffffffbbbbbbfccfbbbbfcccfbbfbbf.........
.......fbbfbbffccfbbbffccfbbcccbbbbbbbbcccbbfccffbbbfccffbbfbbf.........
.......fbbfbbffffffffffccffbcfcbbbffbbbcfcbffccffffffffffbbfbbf.........
.......fbbbfffffffffffffffcbcfcbbbbbbbbcfcbcfffffffffffffffbbbf.........
.......fbbbfff....ffffffffcbcfcbbbbbbbbcfcbcffffffff....fffbbbf.........
.......fffffff....ffffffffcbcfcbbbbbbbbcfcbcffffffff....fffffff.........
.......fffffff....ffffffffcbcfcbbbbbbbbcfcbcffffffff....fffffff.........
.......ffffffff...ffffffffcbcfcbbbbbbbbcfcbcffffffff...ffffffff.........
........ffffffff..ffffffffcbcfcbbbbbbbbcfcbcffffffff..ffffffff..........
.........fffffff..ffffffffcccfccccccccccfcccffffffff..fffffff...........
..........fffff...ffffffffffffffffffffffffffffffffff...fffff............
..........ffff.....ffffffffffffffffffffffffffffffff.....ffff............
...........ff........ffffcffffffffffffffffffcffff........ff.............
.....................fffffcffffffffffffffffcfffff.......................
...................ffffffffcfffffccccfffffcffffffff.....................
..................ffccfcfffffffffccccfffffffffcfccff....................
..................ffccfcffffffcffccccffcffffffcfccff....................
..................fcccfccfffffccfccccfccfffffccfcccf....................
..................fcccfcccffffccfccccfccffffcccfcccf....................
..................fcccfcccffffffffffffffffffcccfcccf....................
..................fcccfcccff.ffffffffffff.ffcccfcccf....................
..................ffccfcccff.ffffffffffff.ffcccfccff....................
..................ffffffffff.fffccccccfff.ffffffffff....................
...................fffffff...ffffffffffff...fffffff.....................
....................ffffff...ffffffffffff...ffffff......................
.....................fcccf....ffccccccff....fcccf.......................
......................fff.....ffffffffff.....fff........................
...............................ffffffff.................................
.................................ffff...................................
........................................................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
